### PR TITLE
Fixes #69 fixing scrapping typos

### LINKED ISSUE #69: typo in packagist description
> A browser testing and web __scrapping__ library for PHP and Symfony.

scrapping should be "scraping"

### PR DESCRIPTION
**Pull request by ChangePlaces**
as requested #69

### CODE REVIEW

**Comment by ChangePlaces** [comment]
I don't think the error " Ignored error pattern /Parameter #1 \$value of method Symfony\\Component\\DomCrawler\\Field\\ChoiceFormField::select\(\) expects string, array<int, string> given\./ was not matched in reported errors. " is anything to do with this pr!

**Comment by stof** [comment]
yeah, that ignore rule is not needed anymore, because the upstream phpdoc has been fixed in https://github.com/symfony/symfony/pull/27849

**Comment by ChangePlaces** [comment]
I haven't touched any files other than the `composer.json`, so I surely don't have to pull anything? Can this not be merged without all green?

**Comment by dunglas** [comment]
Thanks @ChangePlaces!

**Pull request merged**
