### PR TITLE
Allow Symfony 7.0

### PR DESCRIPTION
**Pull request by kbond**

### CODE REVIEW

**Comment by Chris53897** [comment]
Maybe it is time to bump minimum version from 5.3 to 5.4 (LTS)? Maybe in an seperate PR.
https://symfony.com/releases

**Comment by dunglas** [comment]
LGTM but we need to make Psalm happy before merging. Maybe should we run the workflow with Symfony 7?

**Comment by kbond** [comment]
> Maybe should we run the workflow with Symfony 7?

I did this - CI's happy now.

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Thank you!

**Pull request merged**
