### PR TITLE
Better support for non-standard webfolder

### PR DESCRIPTION
**Pull request by Nyholm**
This allows you to use config like: 
```xml
<php>
    <server name="PANTHER_WEB_SERVER_DIR" value="./web/" />
</php>
```

### CODE REVIEW

**Comment by dunglas** [comment]
Hi @Nyholm, I'll tag a new version soon. Can you just rebase and run PHP CS Fixer please? Thanks!

**Comment by Nyholm** [comment]
Of course. I've rebased the PR and fixed CS issues.

**Comment by dunglas** [comment]
Thanks @Nyholm!

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
