### PR TITLE
Add DomCrawler/Field/FileFormField

### PR DESCRIPTION
**Pull request by robertfausk**
...cause it is not implemented yet.

### CODE REVIEW

**Comment by robertfausk** [comment]
I'm unsure about test structure atm. 

Option A: I could put it in ```FormTest::testFormFields``` next to tests for ```ChoiceFormField``` and extend ```fixtures/form.html``` by a file upload field.

Option B: I could put in a separate file ```tests/DomCrawler/Field/FileFormFieldTest.php``` and create a new fixture file ```fixtures/file_form_field.html```.

@dunglas Which one do you prefer?

**Comment by dunglas** [comment]
Both options are ok!

**Comment by robertfausk** [comment]
Thx for ultra fast feedback. I chose option B :)

Concerning tests I still need to implement ```FileFormField::setValue``` for ```testFileUploadWithInvalidValue```. I just recognized this right now.

**Comment by robertfausk** [comment]
> Concerning tests I still need to implement `FileFormField::setValue` for `testFileUploadWithInvalidValue`. I just recognized this right now.

Hmm, I could not find a good solution for different behaviors of goutte and panther when trying to set an invalid file path to file upload. Goutte returns an array with additional information and panther can only return a string and is throwing an exception in current implementation.

If this is ok, then I'm also fine and this PR is ready for review. :relaxed: 
Otherwise any help is appreciated. :sos:

**Comment by robertfausk** [comment]
I have reworked FileFormField.

One problem I encountered is when FormField is "recreated" by a form, e.g. when using in
```PHP
$fileFormField = $form['file_upload'];
$fileFormField->setValue($this->getUploadFilePath(self::$uploadFileName));
$this->assertContains(self::$uploadFileName, $form['file_upload']->getValue());
```
In this case there will be a new instance of FileFormField be created instead of using the already created one. The new one differs from first one. This is cause of ```Symfony\Component\DomCrawler\Form``` which handles a ```FormFieldRegistry``` internally and won't create a new instance.
I've implemented a workaround in this PR which resets the value of FileFormField but there is a drawback: The size of the file is incorrect.
I've not a private field $fields in ```Symfony\Component\Panther\DomCrawler\Form``` cause this would have increased PR size too much IMO. But I can provide a PR for this too if desired.

Hope I'm not completely failing atm.

**Comment by dunglas** [comment]
Thanks @robertfausk

**Pull request merged**
