### PR TITLE
Add Test for #326

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
This basically should prove #326. It happens for also with Github Actions.

If I manually start it and use that with Panther, it works.

### CODE REVIEW

**Comment by dunglas** [comment]
A workaround could be to use Symfony CLI (if available) instead of the PHP Webserver (which isn't designed to handle high loads). What do you think @fabpot?

**Comment by dpfaffenbauer** [comment]
that is how I solved it currently to run my suite.

I'd be happy to create a PR if symfony cli is a valid option?

**Comment by fabpot** [comment]
Sure, if you have PHP FPM available, it will definitely help.

**Comment by dpfaffenbauer** [comment]
this might be the reason: https://bugs.php.net/bug.php?id=79514

**Pull request closed without merging**
