### PR TITLE
Adding the zip extension to the CI process

### PR DESCRIPTION
**Pull request by halfer**
The CI for Panther is missing the zip extension. I am proposing this change to fix that.

### CODE REVIEW

**Comment by halfer** [comment]
I assume the static analysis was failing anyway - this change could not have affected that IMO.

**Comment by halfer** [comment]
FYI @dunglas @nusje2000

**Review by nusje2000 — APPROVED** [review]

**Review by dunglas — APPROVED** [review]

**Comment by nusje2000** [comment]
I've opened a PR to this branch to fix the static analysis: https://github.com/halfer/panther/pull/1

**Comment by dunglas** [comment]
Thanks @halfer

**Pull request merged**
