### PR TITLE
fix email field with existing value

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
If an input field of type "email" already has a value, the field value is not reset, it's getting appended. this fixes it.

### CODE REVIEW

**Comment by dunglas** [comment]
This bug probably also affect other types don't you think? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#%3Cinput%3E_types

**Comment by dpfaffenbauer** [comment]
Very likely. But didn’t come so far yet. But I will come along those types as well in the future and could provide separate PRs

**Comment by dpfaffenbauer** [comment]
FYI: added further tests for number

**Comment by dunglas** [comment]
Thanks @dpfaffenbauer

**Pull request merged**
