### PR TITLE
Client::waitFor() returns a crawler

### PR DESCRIPTION
**Pull request by maidmaid**
In addition to #102, I think that `Client::waitFor()` should directly return an updated crawler.

### CODE REVIEW

**Comment by maidmaid** [comment]
Could you check again ? It looks like unrelated now.

**Comment by dunglas** [comment]
Juste execute `php-cs-fixer fix` and it will be alright!

**Comment by maidmaid** [comment]
Done :)

**Comment by dunglas** [comment]
Thanks Dany!

**Pull request merged**
